name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: pnpm i
      - run: pnpm lint
      - run: pnpm test:types
      - run: pnpm build
      - run: pnpm vitest --coverage
      - uses: codecov/codecov-action@v4
